export const MERCHANT_DATABASE = {
  'Supermarket': [
    'woolworths', 'woolies', 'coles', 'aldi', 'iga', 'foodworks',
    'grocery', 'supermarket', 'groceries',
    'harris farm', 'organic', 'fresh', 'fruit', 'veg', 'market',
    'butcher', 'deli',
  ],
  'Eating & Drinking Out': [
    'mcdonalds', 'mcdonald', 'kfc', 'hungry jacks', 'subway', 'dominos', 'pizza hut',
    'restaurant', 'bistro', 'bakery',
    'uber eats', 'menulog', 'deliveroo', 'doordash',
    'food', 'dining', 'lunch', 'dinner', 'breakfast', 'takeaway', 'take away',
    'grill', 'kitchen', 'eatery', 'noodle', 'sushi', 'thai', 'italian', 'chinese',
    'pizza', 'burger', 'chicken', 'fish and chips', 'kebab', 'poke',
    'vietnamese', 'japanese', 'korean', 'mexican', 'indian', 'greek',
    'bar', 'pub', 'hotel', 'tavern', 'brewery', 'brewing', 'taphouse', 'alehouse',
    'nightclub', 'club', 'lounge', 'cocktail bar', 'wine bar',
    'felons', 'little bang', 'balter', 'stone and wood', 'green beacon',
  ],
  'Coffee': [
    'cafe', 'coffee', 'espresso', 'barista', 'roasters', 'roastery', 'brew', 'bean', 'beans',
    'starbucks', 'gloria jeans', 'the coffee club', 'zarraffa',
    'campos', 'toby estate', 'allpress', 'single o', 'pablo', 'rusty',
    'latte', 'cappuccino', 'flat white', 'macchiato', 'mocha',
    'cup', 'grind', 'espresso bar', 'coffee bar', 'daily grind',
    'coffee shop', 'coffeehouse', 'coffee house', 'java', 'bean bar',
    'the grounds', 'single origin', 'specialty coffee', 'artisan coffee',
    'brewtown', 'coffee co', 'roasting', 'coffee roasting',
  ],
  'Alcohol': [
    'liquor', 'bottle shop', 'dan murphy', 'bws', 'vintage cellars', 'first choice',
    'wine', 'beer', 'spirits', 'brewhouse', 'winery', 'cellar',
  ],
  'Transport': [
    'shell', 'bp', 'caltex', 'ampol', '7-eleven', 'servo', 'petrol', 'fuel', 'gas station',
    'uber', 'taxi', 'cab', 'ola', 'didi', 'shebah', 'lyft',
    'opal', 'myki', 'transport', 'metro', 'train', 'bus', 'tram', 'ferry',
    'parking', 'toll', 'e-toll', 'etoll', 'rego', 'registration',
    'mechanic', 'service', 'tyre', 'tire', 'car wash', 'carwash', 'automotive', 'auto',
    'airport', 'flight', 'qantas', 'virgin', 'jetstar', 'airline',
    'car rental', 'rental car', 'hertz', 'budget', 'thrifty', 'europcar',
    'repairs', 'smash', 'panel', 'detailing',
  ],
  'Entertainment': [
    'cinema', 'movie', 'hoyts', 'event', 'village', 'reading',
    'gaming', 'playstation', 'xbox', 'nintendo', 'steam', 'game',
    'concert', 'ticketek', 'ticketmaster', 'festival', 'show', 'theatre',
    'sports', 'amusement', 'theme park',
  ],
  'Shopping': [
    'kmart', 'target', 'big w', 'myer', 'david jones',
    'bunnings', 'mitre 10', 'hardware', 'ikea',
    'jb hi-fi', 'jb hifi', 'harvey norman', 'good guys', 'electronics',
    'amazon', 'ebay', 'catch', 'kogan', 'online',
    'chemist', 'pharmacy', 'priceline', 'chemist warehouse',
    'clothing', 'fashion', 'shoes', 'apparel', 'retail',
    'officeworks', 'office', 'stationary',
    'jewel', 'gift', 'flower', 'florist',
  ],
  'Bills': [
    'telstra', 'optus', 'vodafone', 'phone', 'mobile', 'internet', 'nbn',
    'electricity', 'gas', 'water', 'energy', 'agl', 'origin', 'utilities',
    'council', 'rates', 'strata',
    'insurance', 'aami', 'nrma', 'budget direct', 'youi',
    'bank', 'interest', 'loan', 'payment', 'fee',
  ],
  'Subscriptions & Memberships': [
    'netflix', 'spotify', 'disney', 'stan', 'binge', 'paramount', 'apple tv',
    'youtube premium', 'amazon prime', 'hbo', 'streaming',
    'subscription', 'membership', 'monthly', 'annual', 'yearly',
    'gym', 'fitness', 'anytime fitness', 'f45', 'crossfit', 'yoga', 'pilates',
    'patreon', 'onlyfans', 'substack',
    'adobe', 'microsoft 365', 'office 365', 'dropbox', 'google one',
    'icloud', 'storage', 'cloud',
    'audible', 'kindle unlimited', 'scribd',
  ],
  'Rent & Mortgage': [
    'rent', 'rental', 'lease', 'landlord', 'tenant',
    'mortgage', 'home loan', 'housing loan',
    'real estate', 'property management', 'ray white', 'lj hooker',
    'realestate.com', 'domain', 'property manager',
    'rent payment', 'monthly rent', 'weekly rent',
    'mortgage payment', 'home repayment', 'loan repayment',
  ],
  'Health': [
    'pharmacy', 'chemist', 'medical', 'doctor', 'gp', 'clinic',
    'dentist', 'dental', 'orthodont',
    'physio', 'chiropract', 'massage', 'therapy', 'therapist',
    'hospital', 'health', 'medicare', 'bupa', 'medibank',
    'optical', 'optom', 'eye', 'glasses', 'vision',
    'vitamin', 'supplement', 'wellness',
  ],
  'Kids': [
    'childcare', 'child care', 'daycare', 'day care', 'kindy', 'kindergarten',
    'school', 'tuition', 'tutoring', 'education',
    'afterschool', 'before school', 'vacation care',
    'kids', 'children', 'child', 'baby', 'toddler',
    'toys', 'toy store', 'toys r us',
    'nappies', 'diapers', 'formula', 'baby food',
    'kids clothing', 'childrens', 'baby clothes',
    'sports club', 'swimming lessons', 'dance class', 'music lessons',
    'school fees', 'excursion', 'camp', 'uniform',
    'birthday party', 'kids party',
  ],
  'Holiday': [
    'hotel', 'motel', 'accommodation', 'airbnb', 'booking.com', 'expedia',
    'holiday', 'vacation', 'resort', 'travel', 'tourism',
    'airline', 'flight', 'qantas', 'virgin', 'jetstar',
    'cruise', 'tour', 'attraction', 'theme park',
  ],
};
